export const bgColor: Record<string, string> = {
    'smartphones': 'bg-blue-400',
    'laptops': 'bg-purple-500',
    'fragrances': 'bg-pink-600',
    'skincare': 'bg-green-500',
    'groceries': 'bg-yellow-400',
    'home-decoration': 'bg-indigo-500',
    'furniture': 'bg-red-400',
    'tops': 'bg-teal-500',
    'womens-dresses': 'bg-pink-500',
    'womens-shoes': 'bg-red-600',
    'mens-shirts': 'bg-blue-600',
    'mens-shoes': 'bg-indigo-600',
    'mens-watches': 'bg-yellow-500',
    'womens-watches': 'bg-purple-600',
    'womens-bags': 'bg-green-600',
    'womens-jewellery': 'bg-teal-600',
    'sunglasses': 'bg-gray-500',
    'automotive': 'bg-red-500',
    'motorcycle': 'bg-blue-500',
    'lighting': 'bg-yellow-600',
}

export const shadowColor: Record<string, string> = {
    'smartphones': 'hover:shadow-blue-600 shadow-lg border-2 border-blue-600',
    'laptops': 'hover:shadow-purple-600 shadow-lg border-2 border-purple-600',
    'fragrances': 'hover:shadow-pink-600 shadow-lg border-2 border-pink-600',
    'skincare': 'hover:shadow-green-600 shadow-lg border-2 border-green-600',
    'groceries': 'hover:shadow-yellow-600 shadow-lg border-2 border-yellow-600',
    'home-decoration': 'hover:shadow-indigo-600 shadow-lg border-2 border-indigo-600',
    'furniture': 'hover:shadow-red-600 shadow-lg border-2 border-red-600',
    'tops': 'hover:shadow-teal-600 shadow-lg border-2 border-teal-600',
    'womens-dresses': 'hover:shadow-pink-600 shadow-lg border-2 border-pink-600',
    'womens-shoes': 'hover:shadow-red-600 shadow-lg border-2 border-red-600',
    'mens-shirts': 'hover:shadow-blue-600 shadow-lg border-2 border-blue-600',
    'mens-shoes': 'hover:shadow-indigo-600 shadow-lg border-2 border-indigo-600',
    'mens-watches': 'hover:shadow-yellow-600 shadow-lg border-2 border-yellow-600',
    'womens-watches': 'hover:shadow-purple-600 shadow-lg border-2 border-purple-600',
    'womens-bags': 'hover:shadow-green-600 shadow-lg border-2 border-green-600',
    'womens-jewellery': 'hover:shadow-teal-600 shadow-lg border-2 border-teal-600',
    'sunglasses': 'hover:shadow-gray-600 shadow-lg border-2 border-gray-600',
    'automotive': 'hover:shadow-red-600 shadow-lg border-2 border-red-600',
    'motorcycle': 'hover:shadow-blue-600 shadow-lg border-2 border-blue-600',
    'lighting': 'hover:shadow-yellow-600 shadow-lg border-2 border-yellow-600',
}

